// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpsiwjuegmbtkpbnrpsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwc2l3anVlZ21idGtwYm5ycHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjMyNDUsImV4cCI6MjA2NjI5OTI0NX0.OMi6rVED28F0YzkxBa5rYYwRqjIlAbpR2rRdSg_-Eug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);