
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyprfzqpmjhagsfivavd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cHJmenFwbWpoYWdzZml2YXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjk2ODgsImV4cCI6MjA2NTg0NTY4OH0.9pPEZqx113L_LXWEclojrdVGZl1xRs31kQVlYBAOM6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined
  }
});

// Add debugging
console.log('Supabase client initialized');
console.log('URL:', SUPABASE_URL);
console.log('Key starts with:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
